DROP TABLE IF EXISTS `ACCOUNT`;
CREATE TABLE `ACCOUNT`
(
    `ID` bigint(20) NOT NULL AUTO_INCREMENT,
    `ACCOUNT_ID` varchar(40) NOT NULL COMMENT '账户id',
    `EVENT_STATUS` bigint(20) NOT NULL DEFAULT 0 COMMENT '状态(测试agg事件)',
    `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `LAST_UPDATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最近更新时间',
    `VERSION` int(11) DEFAULT '1' COMMENT '版本号',
    PRIMARY KEY (`ID`)
);

CREATE UNIQUE INDEX ON ACCOUNT(ACCOUNT_ID);

DROP TABLE IF EXISTS `SUB_ACCOUNT`;
CREATE TABLE `SUB_ACCOUNT`
(
    `ID` bigint(20) NOT NULL AUTO_INCREMENT,
    `ACCOUNT_ID` varchar(40) NOT NULL COMMENT '子账户id',
    `PARENT_ID` varchar(40) NOT NULL COMMENT '主账户主键',
    `EVENT_STATUS` bigint(20) NOT NULL DEFAULT 0 COMMENT '状态(测试agg事件)',
    `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `LAST_UPDATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最近更新时间',
    PRIMARY KEY (`ID`)
);

CREATE UNIQUE INDEX ON SUB_ACCOUNT(ACCOUNT_ID);
CREATE INDEX ON SUB_ACCOUNT(PARENT_ID);