server:
  port: 12332
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: aggregate-framework-server
  datasource:
    url: jdbc:h2:mem:quartz;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: root
    password: welcome1
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2
  agg:
    storage:
      storage-type: redis
      redis:
        host: 127.0.0.1
        port: 6379
        database: 0
        pool-config:
          max-total: 100
          max-idle: 100
          min-idle: 10
          max-wait-millis: 300
    recovery:
      quartz-clustered: true
      quartz-data-source-url: jdbc:h2:mem:quartz
      quartz-data-source-driver: org.h2.Driver
      quartz-data-source-user: root
      quartz-data-source-password: welcome1
    registry:
      registry-type: direct
      cluster-name: default
    remoting:
      listen-port: 2332
logging:
  level:
    root: info