server:
  port: 12332
  servlet:
    context-path: /${spring.application.name}

logging:
  level:
    root: info

spring:
  application:
    name: aggregate-framework-server
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  agg:
    #    request-process-thread-queue-capacity: 1024
    storage:
      #      kryo-pool-size: 512
      storage-type: redis
      jdbc:
        password: 123456
      redis:
        host: 127.0.0.1
        port: 6379
        database: 0
        pool-config:
          max-total: 100
          max-idle: 100
          min-idle: 10
          max-wait-millis: 300
      redis-cluster:
        max-attempts: 5
        so-timeout: 300
        connection-timeout: 1000
        nodes:
          - host: 192.168.75.140
            port: 6379
          - host: 192.168.75.140
            port: 6380
          - host: 192.168.75.140
            port: 6381
          - host: 192.168.75.140
            port: 6382
          - host: 192.168.75.140
            port: 6383
          - host: 192.168.75.140
            port: 6384
      shard-redis:
        nodes:
          - host: 127.0.0.1
            port: 6379
          - host: 127.0.0.1
            port: 6380
          - host: 127.0.0.1
            port: 6381
    recovery:
      #      recovery-enabled: true
      #      update-job-forcibly: false
      quartz-clustered: true
      quartz-data-source-url: jdbc:mysql://localhost:3306/AGG_SERVER?useSSL=false&allowPublicKeyRetrieval=true
      quartz-data-source-driver: com.mysql.jdbc.Driver
      quartz-data-source-user: root
      quartz-data-source-password: 123456
      max-retry-count: 3
    registry:
      registry-type: direct
      cluster-name: default
    #      zookeeper:
    #        connect-string: 127.0.0.1:2181
    #        max-retries: 4
    #      nacos:
    #        server-addr: 127.0.0.1:8848
    remoting:
      listen-port: 2332
