CREATE TABLE `AGG_TRANSACTION_CONFIG`
(
    `ID`             int(11)      NOT NULL AUTO_INCREMENT,
    `REDIS_HOST`     varchar(100) NOT NULL,
    `REDIS_PORT`     int(11)      NOT NULL,
    `REDIS_PASSWORD` varchar(100) DEFAULT NULL,
    `REDIS_DATABASE` int(100)     NOT NULL,
    `DOMAIN`         varchar(100) NOT NULL,
    `CREATE_TIME`    datetime     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_DOMAIN` (`DOMAIN`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;