export const domainsData = [
    "AGG:ACC",
    "AGG:ADV:CLE",
    "AGG:ASB",
    "AGG:AUT",
    "AGG:BIZ_ALBUM",
    "AGG:CAS",
    "AGG:CBK",
    "AGG:CHT",
    "AGG:CLE",
    "AGG:COUPON",
    "AGG:CPT",
    "AGG:FREE_LISTEN",
    "AGG:FULFILL",
    "AGG:IAP",
    "AGG:IPP",
    "AGG:IVC",
    "AGG:JVIP",
    "AGG:MEM",
    "AGG:MSP",
    "AGG:OPEN",
    "AGG:ORD",
    "AGG:PAY-ACC",
    "AGG:PAY-ALB",
    "AGG:PAY-ORD",
    "AGG:PAY-PRD",
    "AGG:PCG",
    "AGG:PGN",
    "AGG:PGW",
    "AGG:PMA",
    "AGG:PMP",
    "AGG:PRC",
    "AGG:PRD",
    "AGG:PRDI",
    "AGG:PTD",
    "AGG:REFUND-PRD",
    "AGG:REP",
    "AGG:RFD",
    "AGG:RPT",
    "AGG:SBP",
    "AGG:SHOP",
    "AGG:SIN",
    "AGG:SPT",
    "AGG:SRE",
    "AGG:SUB",
    "AGG:SUB-SCD",
    "AGG:TPT",
    "AGG:TR-CN",
    "AGG:TR-PG",
    "AGG:TRD-LGT",
    "AGG:TRD-ORD",
    "AGG:TRD-SPT",
    "AGG:TRD-TRS",
    "AGG:UGC",
    "AGG:UPP",
    "AGG:VCR",
    "AGG:VIP",
    "AGG:VIP-CLUB",
    "AGG:VIP-SUPP",
    "AGG:VIP:RESOUCE:CONFIG",
    "AGG:VL",
    "AGG:V_P_R",
    "AGG:XAC",
    "text",
];

export const listData = {
    pages: 1,
    pageSize: 20,
    transactions: [
        {
            status: "Trying",
            type: "Root",
            retried: "100",
            createTime: "2020-04-09 14:22:25",
            lastUpdateTime: "2020-04-09 14:22:25",
            content:
                '{"createTime":1586413345237,"lastUpdateTime":1586413345237,"participant":{"invocation":{"args":[{"pricedOrder":{"id":1,"merchantOrderNo":"OR1586413342796","new":false,"orderLines":[{"new":true,"pricedOrder":{"$ref":"$.participant.invocation.args[0].pricedOrder"},"productId":1,"totalAmount":10}],"statusId":0,"totalAmount":10,"uncommittedDomainEvents":[{"messageType":"DOMAIN_EVENT","payload":{"$ref":"$.participant.invocation.args[0]"},"payloadType":"org.aggregateframework.sample.quickstart.command.domain.event.OrderPlacedEvent"}],"version":1}}],"methodName":"handleOrderCreatedEvent","parameterTypes":["org.aggregateframework.sample.quickstart.command.domain.event.OrderPlacedEvent"],"targetClass":"org.aggregateframework.sample.quickstart.command.eventhandler.OrderHandler","transactionCheckMethod":"x"},"xid":{"branchQualifier":"v9BEJ3glQaSNmdyyOGZV9A==","formatId":1,"globalTransactionId":"mvf7TiiRRv6AGdVbRDjEyA=="}},"retriedCount":0,"status":"TRYING","transactionType":"ROOT","version":1,"xid":{"branchQualifier":"WzEbYa47TSKWiJdfoY21Dw==","formatId":1,"globalTransactionId":"70Abk2/8TlmEtr+S8viW8w=="}}',
            globalTxId: "9a9ddc4f-c7c5-39f8-a3c3-af5ad3d39117",
            branchQualifier: "3918d02d-8255-3c85-bd3b-197096f8403a",
            key:
                "text9a9ddc4f-c7c5-39f8-a3c3-af5ad3d39117:3918d02d-8255-3c85-bd3b-197096f8403a",
        },
    ],
    pageNum: 1,
};
